### ISSUE TITLE
Does not work on catalina

### ISSUE THREAD

**Issue by ITRecords38** [Sesquipedalian/margins-uebersicht#1]
Hi,

I just tested but the script displays errors.

Thanks

**Comment by Sesquipedalian** [comment]
It’s working on my Macs running Catalina. What do the errors say?

**Comment by ITRecords38** [comment]
already very happy that it works on this system :)

here is error.

Thanks

<img width="536" alt="error" src="https://user-images.githubusercontent.com/19632490/73540415-25b59e80-4430-11ea-9bc8-480591e1274f.png">

**Comment by Sesquipedalian** [comment]
I see. That looks legit. My guess is that you created a new user when you installed Catalina and you've never adjusted the size of your Dock at all. If you just want the error to go away for now, open the Dock preference pane in System Preferences and move the Size slider around (you can put it back to the same position afterwards). I will, however, add some error checking code to handle an unset value.

**Comment by ITRecords38** [comment]
#Update

I just did a refresh and it worked well

concerning the user I kept the same after having made my installation. I just put it to the minimum and the error always remains there without any change. 

macOS Catalina 10.15.3

Thanks

**Comment by GrimlocK38** [comment]
on the other hand I don't see the difference applied.

**Comment by ITRecords38** [comment]
it works when we set up other widgets. it is me who is misread. Sorry :)
